CREATE database inegi;
use inegi;

CREATE DATABASE IF NOT EXISTS inegi;
USE inegi;

-- distrito

CREATE TABLE datos_por_distrito (
    ENTIDAD TEXT,
    NOM_ENT TEXT,
    DISTRITO TEXT,
    INDIGENA TEXT,
    COMPLEJIDA TEXT,
    POBTOT DOUBLE, POBFEM DOUBLE, POBMAS DOUBLE, P_0A2 DOUBLE, P_0A2_F DOUBLE, P_0A2_M DOUBLE, P_0A17 DOUBLE, 
    P_3YMAS DOUBLE, P_3YMAS_F DOUBLE, P_3YMAS_M DOUBLE, P_5YMAS DOUBLE, P_5YMAS_F DOUBLE, P_5YMAS_M DOUBLE, 
    P_12YMAS DOUBLE, P_12YMAS_F DOUBLE, P_12YMAS_M DOUBLE, P_15YMAS DOUBLE, P_15YMAS_F DOUBLE, P_15YMAS_M DOUBLE, 
    P_18YMAS DOUBLE, P_18YMAS_F DOUBLE, P_18YMAS_M DOUBLE, P_3A5 DOUBLE, P_3A5_F DOUBLE, P_3A5_M DOUBLE, 
    P_6A11 DOUBLE, P_6A11_F DOUBLE, P_6A11_M DOUBLE, P_8A14 DOUBLE, P_8A14_F DOUBLE, P_8A14_M DOUBLE, 
    P_12A14 DOUBLE, P_12A14_F DOUBLE, P_12A14_M DOUBLE, P_15A17 DOUBLE, P_15A17_F DOUBLE, P_15A17_M DOUBLE, 
    P_18A24 DOUBLE, P_18A24_F DOUBLE, P_18A24_M DOUBLE, P_15A49_F DOUBLE, P_60YMAS DOUBLE, P_60YMAS_F DOUBLE, 
    P_60YMAS_M DOUBLE, REL_H_M DOUBLE, POB0_14 DOUBLE, POB15_64 DOUBLE, POB65_MAS DOUBLE, POB_EDADNE DOUBLE, 
    PROM_HNV DOUBLE, PNACENT DOUBLE, PNACENT_F DOUBLE, PNACENT_M DOUBLE, PNACOE DOUBLE, PNACOE_F DOUBLE, 
    PNACOE_M DOUBLE, PRES2015 DOUBLE, PRES2015_F DOUBLE, PRES2015_M DOUBLE, PRESOE15 DOUBLE, PRESOE15_F DOUBLE, 
    PRESOE15_M DOUBLE, P3YM_HLI DOUBLE, P3YM_HLI_F DOUBLE, P3YM_HLI_M DOUBLE, P3HLINHE DOUBLE, P3HLINHE_F DOUBLE, 
    P3HLINHE_M DOUBLE, P3HLI_HE DOUBLE, P3HLI_HE_F DOUBLE, P3HLI_HE_M DOUBLE, P5_HLI DOUBLE, P5_HLI_NHE DOUBLE, 
    P5_HLI_HE DOUBLE, PHOG_IND DOUBLE, POB_AFRO DOUBLE, POB_AFRO_F DOUBLE, POB_AFRO_M DOUBLE, PCON_DISC DOUBLE, 
    PCDISC_MOT DOUBLE, PCDISC_VIS DOUBLE, PCDISC_LEN DOUBLE, PCDISC_AUD DOUBLE, PCDISC_M_A DOUBLE, PCDISC_MEN DOUBLE, 
    PCON_LIMI DOUBLE, PCLIM_CSB DOUBLE, PCLIM_VIS DOUBLE, PCLIM_HACO DOUBLE, PCLIM_OAUD DOUBLE, PCLIM_MOT2 DOUBLE, 
    PCLIM_RE_C DOUBLE, PCLIM_PMEN DOUBLE, PSIND_LIM DOUBLE, P3A5_NOA DOUBLE, P3A5_NOA_F DOUBLE, P3A5_NOA_M DOUBLE, 
    P6A11_NOA DOUBLE, P6A11_NOAF DOUBLE, P6A11_NOAM DOUBLE, P12A14NOA DOUBLE, P12A14NOAF DOUBLE, P12A14NOAM DOUBLE, 
    P15A17A DOUBLE, P15A17A_F DOUBLE, P15A17A_M DOUBLE, P18A24A DOUBLE, P18A24A_F DOUBLE, P18A24A_M DOUBLE, 
    P8A14AN DOUBLE, P8A14AN_F DOUBLE, P8A14AN_M DOUBLE, P15YM_AN DOUBLE, P15YM_AN_F DOUBLE, P15YM_AN_M DOUBLE, 
    P15YM_SE DOUBLE, P15YM_SE_F DOUBLE, P15YM_SE_M DOUBLE, P15PRI_IN DOUBLE, P15PRI_INF DOUBLE, P15PRI_INM DOUBLE, 
    P15PRI_CO DOUBLE, P15PRI_COF DOUBLE, P15PRI_COM DOUBLE, P15SEC_IN DOUBLE, P15SEC_INF DOUBLE, P15SEC_INM DOUBLE, 
    P15SEC_CO DOUBLE, P15SEC_COF DOUBLE, P15SEC_COM DOUBLE, P18YM_PB DOUBLE, P18YM_PB_F DOUBLE, P18YM_PB_M DOUBLE, 
    GRAPROES DOUBLE, GRAPROES_F DOUBLE, GRAPROES_M DOUBLE, PEA DOUBLE, PEA_F DOUBLE, PEA_M DOUBLE, PE_INAC DOUBLE, 
    PE_INAC_F DOUBLE, PE_INAC_M DOUBLE, POCUPADA DOUBLE, POCUPADA_F DOUBLE, POCUPADA_M DOUBLE, PDESOCUP DOUBLE, 
    PDESOCUP_F DOUBLE, PDESOCUP_M DOUBLE, PSINDER DOUBLE, PDER_SS DOUBLE, PDER_IMSS DOUBLE, PDER_ISTE DOUBLE, 
    PDER_ISTEE DOUBLE, PAFIL_PDOM DOUBLE, PDER_SEGP DOUBLE, PDER_IMSSB DOUBLE, PAFIL_IPRI DOUBLE, PAFIL_OTRA DOUBLE, 
    P12YM_SOLT DOUBLE, P12YM_CASA DOUBLE, P12YM_SEPA DOUBLE, TOTHOG DOUBLE, HOGJEF_F DOUBLE, HOGJEF_M DOUBLE, 
    POBHOG DOUBLE, PHOGJEF_F DOUBLE, PHOGJEF_M DOUBLE, VIVTOT DOUBLE, TVIVHAB DOUBLE, TVIVPAR DOUBLE, VIVPAR_HAB DOUBLE, 
    VIVPARH_CV DOUBLE, TVIVPARHAB DOUBLE, VIVPAR_DES DOUBLE, VIVPAR_UT DOUBLE, OCUPVIVPAR DOUBLE, PROM_OCUP DOUBLE, 
    PRO_OCUP_C DOUBLE, VPH_PISODT DOUBLE, VPH_PISOTI DOUBLE, VPH_1DOR DOUBLE, VPH_2YMASD DOUBLE, VPH_1CUART DOUBLE, 
    VPH_2CUART DOUBLE, VPH_3YMASC DOUBLE, VPH_C_ELEC DOUBLE, VPH_S_ELEC DOUBLE, VPH_AGUADV DOUBLE, VPH_AEASP DOUBLE, 
    VPH_AGUAFV DOUBLE, VPH_TINACO DOUBLE, VPH_CISTER DOUBLE, VPH_EXCSA DOUBLE, VPH_LETR DOUBLE, VPH_DRENAJ DOUBLE, 
    VPH_NODREN DOUBLE, VPH_C_SERV DOUBLE, VPH_NDEAED DOUBLE, VPH_DSADMA DOUBLE, VPH_NDACMM DOUBLE, VPH_SNBIEN DOUBLE, 
    VPH_REFRI DOUBLE, VPH_LAVAD DOUBLE, VPH_HMICRO DOUBLE, VPH_AUTOM DOUBLE, VPH_MOTO DOUBLE, VPH_BICI DOUBLE, 
    VPH_RADIO DOUBLE, VPH_TV DOUBLE, VPH_PC DOUBLE, VPH_TELEF DOUBLE, VPH_CEL DOUBLE, VPH_INTER DOUBLE, 
    VPH_STVP DOUBLE, VPH_SPMVPI DOUBLE, VPH_CVJ DOUBLE, VPH_SINRTV DOUBLE, VPH_SINLTC DOUBLE, VPH_SINCIN DOUBLE, 
    VPH_SINTIC DOUBLE
);


LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/INE_DISTRITO_2020.CSV'
INTO TABLE datos_por_distrito -- Asegúrate que el nombre de la tabla sea el que creaste
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;

SHOW VARIABLES LIKE "secure_file_priv";

-- Entidad
CREATE TABLE datos_por_entidad (
    ENT TEXT,
    NOM_ENT TEXT,
    POBTOT DOUBLE, POBFEM DOUBLE, POBMAS DOUBLE, P_0A2 DOUBLE, P_0A2_F DOUBLE, P_0A2_M DOUBLE, P_0A17 DOUBLE, 
    P_3YMAS DOUBLE, P_3YMAS_F DOUBLE, P_3YMAS_M DOUBLE, P_5YMAS DOUBLE, P_5YMAS_F DOUBLE, P_5YMAS_M DOUBLE, 
    P_12YMAS DOUBLE, P_12YMAS_F DOUBLE, P_12YMAS_M DOUBLE, P_15YMAS DOUBLE, P_15YMAS_F DOUBLE, P_15YMAS_M DOUBLE, 
    P_18YMAS DOUBLE, P_18YMAS_F DOUBLE, P_18YMAS_M DOUBLE, P_3A5 DOUBLE, P_3A5_F DOUBLE, P_3A5_M DOUBLE, 
    P_6A11 DOUBLE, P_6A11_F DOUBLE, P_6A11_M DOUBLE, P_8A14 DOUBLE, P_8A14_F DOUBLE, P_8A14_M DOUBLE, 
    P_12A14 DOUBLE, P_12A14_F DOUBLE, P_12A14_M DOUBLE, P_15A17 DOUBLE, P_15A17_F DOUBLE, P_15A17_M DOUBLE, 
    P_18A24 DOUBLE, P_18A24_F DOUBLE, P_18A24_M DOUBLE, P_15A49_F DOUBLE, P_60YMAS DOUBLE, P_60YMAS_F DOUBLE, 
    P_60YMAS_M DOUBLE, REL_H_M DOUBLE, POB0_14 DOUBLE, POB15_64 DOUBLE, POB65_MAS DOUBLE, POB_EDADNE DOUBLE, 
    PROM_HNV DOUBLE, PNACENT DOUBLE, PNACENT_F DOUBLE, PNACENT_M DOUBLE, PNACOE DOUBLE, PNACOE_F DOUBLE, 
    PNACOE_M DOUBLE, PRES2015 DOUBLE, PRES2015_F DOUBLE, PRES2015_M DOUBLE, PRESOE15 DOUBLE, PRESOE15_F DOUBLE, 
    PRESOE15_M DOUBLE, P3YM_HLI DOUBLE, P3YM_HLI_F DOUBLE, P3YM_HLI_M DOUBLE, P3HLINHE DOUBLE, P3HLINHE_F DOUBLE, 
    P3HLINHE_M DOUBLE, P3HLI_HE DOUBLE, P3HLI_HE_F DOUBLE, P3HLI_HE_M DOUBLE, P5_HLI DOUBLE, P5_HLI_NHE DOUBLE, 
    P5_HLI_HE DOUBLE, PHOG_IND DOUBLE, POB_AFRO DOUBLE, POB_AFRO_F DOUBLE, POB_AFRO_M DOUBLE, PCON_DISC DOUBLE, 
    PCDISC_MOT DOUBLE, PCDISC_VIS DOUBLE, PCDISC_LEN DOUBLE, PCDISC_AUD DOUBLE, PCDISC_M_A DOUBLE, PCDISC_MEN DOUBLE, 
    PCON_LIMI DOUBLE, PCLIM_CSB DOUBLE, PCLIM_VIS DOUBLE, PCLIM_HACO DOUBLE, PCLIM_OAUD DOUBLE, PCLIM_MOT2 DOUBLE, 
    PCLIM_RE_C DOUBLE, PCLIM_PMEN DOUBLE, PSIND_LIM DOUBLE, P3A5_NOA DOUBLE, P3A5_NOA_F DOUBLE, P3A5_NOA_M DOUBLE, 
    P6A11_NOA DOUBLE, P6A11_NOAF DOUBLE, P6A11_NOAM DOUBLE, P12A14NOA DOUBLE, P12A14NOAF DOUBLE, P12A14NOAM DOUBLE, 
    P15A17A DOUBLE, P15A17A_F DOUBLE, P15A17A_M DOUBLE, P18A24A DOUBLE, P18A24A_F DOUBLE, P18A24A_M DOUBLE, 
    P8A14AN DOUBLE, P8A14AN_F DOUBLE, P8A14AN_M DOUBLE, P15YM_AN DOUBLE, P15YM_AN_F DOUBLE, P15YM_AN_M DOUBLE, 
    P15YM_SE DOUBLE, P15YM_SE_F DOUBLE, P15YM_SE_M DOUBLE, P15PRI_IN DOUBLE, P15PRI_INF DOUBLE, P15PRI_INM DOUBLE, 
    P15PRI_CO DOUBLE, P15PRI_COF DOUBLE, P15PRI_COM DOUBLE, P15SEC_IN DOUBLE, P15SEC_INF DOUBLE, P15SEC_INM DOUBLE, 
    P15SEC_CO DOUBLE, P15SEC_COF DOUBLE, P15SEC_COM DOUBLE, P18YM_PB DOUBLE, P18YM_PB_F DOUBLE, P18YM_PB_M DOUBLE, 
    GRAPROES DOUBLE, GRAPROES_F DOUBLE, GRAPROES_M DOUBLE, PEA DOUBLE, PEA_F DOUBLE, PEA_M DOUBLE, PE_INAC DOUBLE, 
    PE_INAC_F DOUBLE, PE_INAC_M DOUBLE, POCUPADA DOUBLE, POCUPADA_F DOUBLE, POCUPADA_M DOUBLE, PDESOCUP DOUBLE, 
    PDESOCUP_F DOUBLE, PDESOCUP_M DOUBLE, PSINDER DOUBLE, PDER_SS DOUBLE, PDER_IMSS DOUBLE, PDER_ISTE DOUBLE, 
    PDER_ISTEE DOUBLE, PAFIL_PDOM DOUBLE, PDER_SEGP DOUBLE, PDER_IMSSB DOUBLE, PAFIL_IPRI DOUBLE, PAFIL_OTRA DOUBLE, 
    P12YM_SOLT DOUBLE, P12YM_CASA DOUBLE, P12YM_SEPA DOUBLE, TOTHOG DOUBLE, HOGJEF_F DOUBLE, HOGJEF_M DOUBLE, 
    POBHOG DOUBLE, PHOGJEF_F DOUBLE, PHOGJEF_M DOUBLE, VIVTOT DOUBLE, TVIVHAB DOUBLE, TVIVPAR DOUBLE, VIVPAR_HAB DOUBLE, 
    VIVPARH_CV DOUBLE, TVIVPARHAB DOUBLE, VIVPAR_DES DOUBLE, VIVPAR_UT DOUBLE, OCUPVIVPAR DOUBLE, PROM_OCUP DOUBLE, 
    PRO_OCUP_C DOUBLE, VPH_PISODT DOUBLE, VPH_PISOTI DOUBLE, VPH_1DOR DOUBLE, VPH_2YMASD DOUBLE, VPH_1CUART DOUBLE, 
    VPH_2CUART DOUBLE, VPH_3YMASC DOUBLE, VPH_C_ELEC DOUBLE, VPH_S_ELEC DOUBLE, VPH_AGUADV DOUBLE, VPH_AEASP DOUBLE, 
    VPH_AGUAFV DOUBLE, VPH_TINACO DOUBLE, VPH_CISTER DOUBLE, VPH_EXCSA DOUBLE, VPH_LETR DOUBLE, VPH_DRENAJ DOUBLE, 
    VPH_NODREN DOUBLE, VPH_C_SERV DOUBLE, VPH_NDEAED DOUBLE, VPH_DSADMA DOUBLE, VPH_NDACMM DOUBLE, VPH_SNBIEN DOUBLE, 
    VPH_REFRI DOUBLE, VPH_LAVAD DOUBLE, VPH_HMICRO DOUBLE, VPH_AUTOM DOUBLE, VPH_MOTO DOUBLE, VPH_BICI DOUBLE, 
    VPH_RADIO DOUBLE, VPH_TV DOUBLE, VPH_PC DOUBLE, VPH_TELEF DOUBLE, VPH_CEL DOUBLE, VPH_INTER DOUBLE, 
    VPH_STVP DOUBLE, VPH_SPMVPI DOUBLE, VPH_CVJ DOUBLE, VPH_SINRTV DOUBLE, VPH_SINLTC DOUBLE, VPH_SINCIN DOUBLE, 
    VPH_SINTIC DOUBLE
);



LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/INE_ENTIDAD_2020.csv'
INTO TABLE datos_por_entidad
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
